#配置端口号  默认8080
server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xiaoshuo?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      password: 123456
#配置日志输出
mybatis-plus:
  type-aliases-package: com.fzy.xiaoshuo.entity
  configuration:
#    配置默认日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  配置假删除
  global-config:
    db-config:
      logic-delete-field: delFlg
      logic-delete-value: 1
      logic-not-delete-value: 0